---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  metrics:
  - name: webcheck
    count: 5
    interval: 3s
    successCondition: "true"
    provider:
      job:
        backoffLimit: 1
        spec:
          template:
            spec:
              containers:
              - name: check
                image: tutum/curl
                command: ["curl", "http://51.159.24.218/"]
              restartPolicy: Never
