---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  metrics:
  - name: webcheck
    successCondition: "true"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "51.159.24.218:5000"
        jsonPath: "{$.ok}"
