---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: colorapi
  labels:
    app: colorapi
spec:
  strategy:
    canary:
      canaryService: canary-colorapi
      analysis:
        templates:
          - templateName: webcheck
        args:
        - name: host
          value: canary-colorapi
      steps:
      - setWeight: 25
      - pause:
          duration: "30s"
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: colorapi
  template:
    metadata:
      labels:
        app: colorapi
    spec:
      containers:
      - name: colorapi
        image: particule/simplecolorapi:1.0
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: colorapi
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: colorapi
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: canary-colorapi
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: colorapi
  type: LoadBalancer

